"""
SAP2000 Visual Scripter - Blockly GUI (PySide6)
=================================================
App principal: editor Blockly embebido + preview Python + consola.

Uso:
    python scripts/blockly/blockly_gui.py
"""

import sys
import json
from pathlib import Path
from typing import Optional

from PySide6.QtWidgets import (
    QApplication, QMainWindow, QWidget, QVBoxLayout, QHBoxLayout,
    QPlainTextEdit, QPushButton, QLabel, QMessageBox, QFileDialog,
    QSplitter, QToolBar, QStatusBar,
)
from PySide6.QtWebEngineWidgets import QWebEngineView
from PySide6.QtWebEngineCore import QWebEngineSettings
from PySide6.QtCore import Qt, QTimer, QUrl, Signal, Slot, QThread
from PySide6.QtGui import QFont, QAction, QKeySequence

try:
    from blockly_transpiler import BlocklyTranspiler
    from blockly_executor import BlocklyScriptExecutor
except ImportError:
    from .blockly_transpiler import BlocklyTranspiler
    from .blockly_executor import BlocklyScriptExecutor


# --- Constants ---

HERE = Path(__file__).resolve().parent
INDEX_HTML = HERE / "index.html"
RECENT_FILE = HERE / ".recent_projects.json"
MAX_RECENT = 5
PREVIEW_INTERVAL_MS = 500


# --- Worker thread for SAP2000 execution ---

class ScriptWorker(QThread):
    """Run script in background thread to keep GUI responsive."""
    finished = Signal(dict)

    def __init__(self, executor, script: str):
        super().__init__()
        self._executor = executor
        self._script = script

    def run(self):
        result = self._executor.run_script(self._script)
        self.finished.emit(result)


# --- Blockly Editor (QWebEngineView) ---

class BlocklyEditor(QWebEngineView):
    """Blockly workspace loaded from index.html."""

    def __init__(self, parent=None):
        super().__init__(parent)
        self._load_html()

    def _load_html(self):
        # Allow file:// pages to fetch remote CDN scripts (Blockly unpkg)
        settings = self.page().settings()
        settings.setAttribute(
            QWebEngineSettings.WebAttribute.LocalContentCanAccessRemoteUrls, True
        )
        if INDEX_HTML.exists():
            self.load(QUrl.fromLocalFile(str(INDEX_HTML)))
        else:
            self.setHtml(
                "<h3 style='color:red;font-family:sans-serif;padding:20px'>"
                "index.html not found.<br>"
                "Run: python scripts/blockly/blockly_generator.py"
                "</h3>"
            )

    def get_workspace_xml(self, callback):
        """Async: get workspace XML via JS callback."""
        self.page().runJavaScript(
            "typeof getWorkspaceXml === 'function' ? getWorkspaceXml() : '<xml></xml>'",
            callback
        )

    def generate_python_js(self, callback):
        """Async: get Python code generated by Blockly JS."""
        self.page().runJavaScript(
            "typeof generatePython === 'function' ? generatePython() : ''",
            callback
        )

    def load_xml(self, xml_str: str):
        """Load workspace from XML string."""
        safe = xml_str.replace("\\", "\\\\").replace("`", "\\`")
        self.page().runJavaScript(
            f"typeof loadWorkspaceXml === 'function' ? loadWorkspaceXml(`{safe}`) : false"
        )

    def clear(self):
        self.page().runJavaScript(
            "typeof clearWorkspace === 'function' ? clearWorkspace() : null"
        )

    def get_block_count(self, callback):
        self.page().runJavaScript(
            "typeof getBlockCount === 'function' ? getBlockCount() : 0",
            callback
        )


# --- Main Application ---

class BlocklyScripterApp(QMainWindow):

    def __init__(self):
        super().__init__()
        self.setWindowTitle("SAP2000 Visual Scripter \u2014 Blockly")
        self.setGeometry(100, 100, 1920, 1080)

        self.transpiler = BlocklyTranspiler()
        self.executor = BlocklyScriptExecutor()
        self.current_xml: Optional[str] = None
        self.current_project_path: Optional[str] = None
        self._recent: list = self._load_recent()
        self._worker: Optional[ScriptWorker] = None

        self._setup_ui()
        self._setup_toolbar()
        self._setup_menu()
        self._setup_statusbar()

        # Preview timer
        self._preview_timer = QTimer()
        self._preview_timer.timeout.connect(self._update_preview)
        QTimer.singleShot(1500, lambda: self._preview_timer.start(PREVIEW_INTERVAL_MS))

        # Connect to SAP2000 after UI is ready
        QTimer.singleShot(500, self._connect_sap2000)

    # --- UI Setup ---

    def _setup_ui(self):
        splitter = QSplitter(Qt.Horizontal)

        # Left: Blockly editor (70%)
        self.editor = BlocklyEditor()
        splitter.addWidget(self.editor)

        # Right: Python preview + console (30%)
        right_widget = QWidget()
        right_layout = QVBoxLayout(right_widget)
        right_layout.setContentsMargins(4, 4, 4, 4)
        right_layout.setSpacing(4)

        # Python Preview
        preview_label = QLabel("Python Preview")
        preview_label.setStyleSheet("font-weight: bold; color: #ccc;")
        right_layout.addWidget(preview_label)

        self.code_preview = QPlainTextEdit()
        self.code_preview.setReadOnly(True)
        self.code_preview.setFont(QFont("Courier New", 9))
        self.code_preview.setPlaceholderText("# Arrastra bloques para generar codigo Python")
        self.code_preview.setStyleSheet(
            "background:#1e1e1e; color:#d4d4d4; border:1px solid #444;"
        )
        right_layout.addWidget(self.code_preview, 40)

        # Console
        console_label = QLabel("Console")
        console_label.setStyleSheet("font-weight: bold; color: #ccc;")
        right_layout.addWidget(console_label)

        self.console = QPlainTextEdit()
        self.console.setReadOnly(True)
        self.console.setFont(QFont("Courier New", 9))
        self.console.setStyleSheet(
            "background:#0d0d0d; color:#a8ff78; border:1px solid #444;"
        )
        right_layout.addWidget(self.console, 60)

        # Run button
        self.btn_run = QPushButton("Run (Ctrl+R)")
        self.btn_run.setStyleSheet(
            "background:#27ae60; color:white; padding:8px; font-weight:bold;"
            "border-radius:4px;"
        )
        self.btn_run.setShortcut(QKeySequence("Ctrl+R"))
        self.btn_run.clicked.connect(self._on_run)
        right_layout.addWidget(self.btn_run)

        splitter.addWidget(right_widget)
        splitter.setSizes([1344, 576])
        self.setCentralWidget(splitter)

    def _setup_toolbar(self):
        tb = self.addToolBar("Main")
        tb.setMovable(False)
        tb.addAction(self._make_action("New", self._on_new, "Ctrl+N"))
        tb.addAction(self._make_action("Open", self._on_open, "Ctrl+O"))
        tb.addAction(self._make_action("Save", self._on_save, "Ctrl+S"))
        tb.addSeparator()
        tb.addAction(self._make_action("Export Python", self._on_export, "Ctrl+E"))
        tb.addSeparator()
        tb.addAction(self._make_action("Clear", self._on_clear))

    def _setup_menu(self):
        menu = self.menuBar()

        file_menu = menu.addMenu("&File")
        file_menu.addAction(self._make_action("&New", self._on_new, "Ctrl+N"))
        file_menu.addAction(self._make_action("&Open...", self._on_open, "Ctrl+O"))
        file_menu.addAction(self._make_action("&Save", self._on_save, "Ctrl+S"))
        file_menu.addAction(self._make_action("Save &As...", self._on_save_as))
        file_menu.addSeparator()
        file_menu.addAction(self._make_action("&Export Python...", self._on_export, "Ctrl+E"))
        file_menu.addSeparator()
        self._recent_menu = file_menu.addMenu("Recent Projects")
        self._update_recent_menu()
        file_menu.addSeparator()
        file_menu.addAction(self._make_action("E&xit", self.close))

        edit_menu = menu.addMenu("&Edit")
        edit_menu.addAction(self._make_action("&Clear All", self._on_clear))

        help_menu = menu.addMenu("&Help")
        help_menu.addAction(self._make_action("&About", self._on_about))

    def _setup_statusbar(self):
        self.status_bar = QStatusBar()
        self.setStatusBar(self.status_bar)
        self.block_count_label = QLabel("Blocks: 0")
        self.status_bar.addWidget(self.block_count_label)
        self.sap_status = QLabel("SAP2000: Disconnected")
        self.sap_status.setStyleSheet("color: #ff9800;")
        self.status_bar.addPermanentWidget(self.sap_status)

    def _make_action(self, text: str, slot, shortcut: str = None) -> QAction:
        action = QAction(text, self)
        action.triggered.connect(slot)
        if shortcut:
            action.setShortcut(QKeySequence(shortcut))
        return action

    # --- SAP2000 Connection ---

    def _connect_sap2000(self):
        result = self.executor.connect(attach_to_existing=True)
        if result["connected"]:
            self.sap_status.setText(f"SAP2000: v{result['version']}")
            self.sap_status.setStyleSheet("color: #27ae60;")
            self._log(f"Connected to SAP2000 v{result['version']}")
        else:
            self.sap_status.setText("SAP2000: Not connected")
            self.sap_status.setStyleSheet("color: #ff9800;")
            self._log("SAP2000 not open -- design mode only")
        self._log("Drag blocks from the toolbox to create a script\n")

    # --- Preview Update ---

    def _update_preview(self):
        def on_xml(xml):
            if not xml:
                return
            self.current_xml = xml
            if "<block" in xml:
                try:
                    python_code = self.transpiler.xml_to_python(xml)
                    self.code_preview.setPlainText(python_code)
                except Exception:
                    pass
            else:
                self.code_preview.clear()
            self.editor.get_block_count(
                lambda n: self.block_count_label.setText(f"Blocks: {n or 0}")
            )

        self.editor.get_workspace_xml(on_xml)

    # --- Actions ---

    def _on_run(self):
        if not self.current_xml or "<block" not in (self.current_xml or ""):
            QMessageBox.warning(self, "Empty", "No blocks in workspace.")
            return

        python_code = self.transpiler.xml_to_python(self.current_xml)
        self._log("\nRunning...")
        self.btn_run.setEnabled(False)

        self._worker = ScriptWorker(self.executor, python_code)
        self._worker.finished.connect(self._on_run_finished)
        self._worker.start()

    def _on_run_finished(self, result: dict):
        self.btn_run.setEnabled(True)
        if result.get("success"):
            self._log(f"Success! ({result.get('execution_time_s', 0):.3f}s)")
            if result.get("stdout"):
                self._log(result["stdout"])
        else:
            self._log(f"Error: {result.get('error', 'Unknown error')}")
            if result.get("stderr"):
                self._log(result["stderr"])

    def _on_export(self):
        if not self.current_xml:
            QMessageBox.warning(self, "Empty", "No blocks in workspace.")
            return
        path, _ = QFileDialog.getSaveFileName(
            self, "Export Python", "", "Python Files (*.py)"
        )
        if path:
            try:
                code = self.transpiler.xml_to_python(self.current_xml)
                Path(path).write_text(code, encoding="utf-8")
                self._log(f"Exported to {path}")
            except Exception as e:
                QMessageBox.critical(self, "Error", str(e))

    def _on_new(self):
        if self.current_xml and "<block" in (self.current_xml or ""):
            reply = QMessageBox.question(
                self, "New Project",
                "Discard current blocks and start new project?",
                QMessageBox.Yes | QMessageBox.No,
                QMessageBox.No,
            )
            if reply != QMessageBox.Yes:
                return
        self.editor.clear()
        self.current_xml = None
        self.current_project_path = None
        self.code_preview.clear()
        self.setWindowTitle("SAP2000 Visual Scripter \u2014 Blockly")

    def _on_open(self):
        path, _ = QFileDialog.getOpenFileName(
            self, "Open Project", "", "Blockly Projects (*.blockly)"
        )
        if path:
            self._open_project(path)

    def _open_project(self, path: str):
        try:
            data = json.loads(Path(path).read_text(encoding="utf-8"))
            xml_str = data.get("workspace_xml", "")
            self.editor.load_xml(xml_str)
            self.current_xml = xml_str
            self.current_project_path = path
            self.code_preview.setPlainText(self.transpiler.xml_to_python(xml_str))
            self.setWindowTitle(f"SAP2000 Visual Scripter \u2014 {Path(path).name}")
            self._add_recent(path)
            self._log(f"Opened: {path}")
        except Exception as e:
            QMessageBox.critical(self, "Error", f"Could not open project:\n{e}")

    def _on_save(self):
        if self.current_project_path:
            self._save_project(self.current_project_path)
        else:
            self._on_save_as()

    def _on_save_as(self):
        if not self.current_xml:
            QMessageBox.warning(self, "Empty", "No blocks in workspace.")
            return
        path, _ = QFileDialog.getSaveFileName(
            self, "Save Project", "", "Blockly Projects (*.blockly)"
        )
        if path:
            self._save_project(path)

    def _save_project(self, path: str):
        try:
            from datetime import datetime
            data = {
                "version": "2.0",
                "workspace_xml": self.current_xml or "<xml></xml>",
                "timestamp": datetime.now().isoformat(),
            }
            Path(path).write_text(json.dumps(data, indent=2), encoding="utf-8")
            self.current_project_path = path
            self.setWindowTitle(f"SAP2000 Visual Scripter \u2014 {Path(path).name}")
            self._add_recent(path)
            self._log(f"Saved: {path}")
        except Exception as e:
            QMessageBox.critical(self, "Error", f"Could not save project:\n{e}")

    def _on_clear(self):
        if QMessageBox.question(
            self, "Clear", "Clear all blocks?",
            QMessageBox.Yes | QMessageBox.No,
            QMessageBox.No,
        ) == QMessageBox.Yes:
            self.editor.clear()
            self.current_xml = None
            self.code_preview.clear()

    def _on_about(self):
        QMessageBox.about(
            self,
            "SAP2000 Visual Scripter \u2014 Blockly",
            "Visual drag-and-drop editor for SAP2000 automation\n\n"
            "v2.0 \u2014 2026\n\n"
            "Drag blocks \u2192 Configure parameters \u2192 Execute\n\n"
            "Shortcuts:\n"
            "  Ctrl+N  New Project\n"
            "  Ctrl+O  Open Project\n"
            "  Ctrl+S  Save Project\n"
            "  Ctrl+R  Run Script\n"
            "  Ctrl+E  Export Python",
        )

    # --- Recent Projects ---

    def _load_recent(self) -> list:
        if RECENT_FILE.exists():
            try:
                return json.loads(RECENT_FILE.read_text(encoding="utf-8"))
            except Exception:
                pass
        return []

    def _save_recent(self):
        RECENT_FILE.write_text(json.dumps(self._recent), encoding="utf-8")

    def _add_recent(self, path: str):
        if path in self._recent:
            self._recent.remove(path)
        self._recent.insert(0, path)
        self._recent = self._recent[:MAX_RECENT]
        self._save_recent()
        self._update_recent_menu()

    def _update_recent_menu(self):
        self._recent_menu.clear()
        if not self._recent:
            self._recent_menu.addAction("(none)").setEnabled(False)
            return
        for path in self._recent:
            action = QAction(Path(path).name, self)
            action.setStatusTip(path)
            action.triggered.connect(lambda checked, p=path: self._open_project(p))
            self._recent_menu.addAction(action)

    # --- Logging ---

    def _log(self, msg: str):
        self.console.appendPlainText(msg)

    # --- Lifecycle ---

    def closeEvent(self, event):
        self._preview_timer.stop()
        self.executor.disconnect()
        super().closeEvent(event)


def main():
    app = QApplication(sys.argv)
    window = BlocklyScripterApp()
    window.show()
    sys.exit(app.exec())


if __name__ == "__main__":
    main()
